# This action goes in the CheatSheetsSeries repository
# TODO: make sure you set up a GH_USERNAME and GH_TOKEN (or password) in secrets with the relevant info
name: update www-cs

on:
  push:
    branches: [ master ]

jobs:   
  update:
    runs-on: ubuntu-latest
  
    steps:
    # posts a dispatch event to the remote repo (which then makes the remote Action run)
    # TODO: change the repository in the curl command to www-project-cheat-sheets
    - name: Update www-test-cs-pull
      run: |
        curl -XPOST -u "${{ secrets.GH_USERNAME}}:${{secrets.GH_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json"  -H "Content-Type: application/json" https://api.github.com/repos/OWASP/www-test-cs-pull/dispatches --data '{"event_type": "build_application"}'
